# Getting Started

## MB5 Lab Checklist {-}

* If you are new to MB5, complete the [Initial Sign-Up Form](https://docs.google.com/forms/d/e/1FAIpQLSdJnP3KO_dCmj-jNPHs0XP2j3q66g1RI6L31dwhCzhwhoJeoA/viewform).
* Read this manual start to finish.
* **BEFORE you begin data collection:**
    * Please ensure that you have carefully read the [MB5 Collaboration Agreement](https://docs.google.com/document/d/1vbTDmH6euda5pJN4uyds3zsnQ1DXrW9wpHogwC-5TSk/edit?usp=sharing) and all of the documentation from the [ManyBabies General Manual](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit?usp=sharing) regarding [ethical research](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit#heading=h.22i70rxou3ha), [authorship](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit#heading=h.9ty2g48mpe0t), [data sharing](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit#heading=h.aunbjkpwxhf3), and [data use](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit#heading=h.6h67zsyeiveg). 
    * Set up your study in consultation with this document. Carefully record any needed deviations from the protocol. Decide on your planned sample size/stopping rule.
    * Complete the Laboratory Questionnaire [insert link], submit Ethics approval and other documentation/materials. 
    * Create and submit your walkthrough video.
    * Run pilot sample through [data validator](https://manybabies.org/validator/).
    * Send email to [mb5@manybabies.org](mb5@manybabies.org) to let the leadership team know that you are ready for ‘greenlighting’. 
    * Wait for your official “greenlight” from the leadership team to begin data collection.
* **Data collection:**
    * Collect your data! 
    * *IMPORTANT: DO NOT begin data collection (other than piloting) until you have been explicitly (and individually) “greenlighted” to do so.*
* **AFTER you finish data collection:**
    * Complete your participant and trial data files in consultation with the data reporting instructions "[Data reporting guidelines]."
    * Submit your data using the [MB5 data upload form](https://docs.google.com/forms/d/e/1FAIpQLSdFYk-gb4yjRYLjSTP1_BVaW-3vLkpJClLoY2BOGDGfIVE5ww/viewform?usp=sf_link).

<br>

***

## Start and End Date
MB5 data collection is scheduled to run from **2024-MM-DD** to **2025-MM-DD**. Labs may join the MB5 project any time during the data collection period, provided that set-up and a formal “green light” is obtained, and data collection can be completed before the end date. However, we understand that there may be disruptions to data collection for various reasons. If you are having trouble meeting this timeframe, please alert the leadership team to discuss possibilities.  


## Ethics approval
It is a good idea to get started on your ethics approvals as soon as possible. Approvals must be in place and a copy submitted to the Drive folder (see Section \@ref(ethics-upload)) before you can obtain a green light to collect data. Contact us [mb5@manybabies.org](mailto:mb5@manybabies.org) if you need advice on obtaining ethics approval. 

MB5 and other ManyBabies projects ask labs to collect a number of [demographic background variables](ADD LINK TO PARTICIPANTS SECTION) to be made public along with the main data, e.g. parental education, sex, etcetera. Not all of those variables are part of the main analysis. Even so, it is highly relevant to collect them for follow-up and secondary analyses, and for checking the representativeness of the sample. Please contact us [mb5@manybabies.org](mailto:mb5@manybabies.org) if your ethics board raises concerns about collecting these data. 

##### Please make sure you have permission to publicly share anonymized raw data (including required demographic info), as this is a condition of participation. {-}

### Video sharing 
We strongly encourage labs (where possible) to store/share video recordings of their testing on [Databrary](https://nyu.databrary.org/), which is a secure site for this purpose. You will need to ensure that you have ethics approval in place to do this, and collect specific consent for this purpose from your participants. In addition, you will become a member of Databrary, which will require approval from your institution, so it’s helpful to start this process early. You can [begin the registration process for Databrary here](https://nyu.databrary.org/user/register?page=create). We are aware that many laboratories, particularly in the European Union, may not be allowed to use Databrary. In these circumstances we encourage labs to use alternative methods for sharing their videos where possible.

### Upload a copy of your ethics approval documentation {#ethics-upload}
Ethics documentation (e.g., IRB approval forms) should be submitted prior to data collection. Ethics forms should be uploaded using the [MB5 Documentation Upload Form](https://docs.google.com/forms/d/e/1FAIpQLScTTmcQl1P1F4UWe95Jo7u5bken40AyAefXCYUJ9iYbnWaG8Q/viewform?usp=sf_link). **Please ensure that all materials uploaded for ethics are clearly labeled in the filename with your LabID (e.g. *babylabPrinceton_ethics.pdf*).** Check [here](https://manybabies.org/labids/) for a complete list of LabIDs to confirm yours before uploading. In some cases, labs will already have approval for MB5 under an “umbrella protocol” (i.e., a protocol that covers multiple studies in one lab). In these cases, the ethics form should still be uploaded as described here.


## Participants and Recruitment

### Age and numbers
The minimum expected contribution is a full sample of 32 babies (preferred, if possible) or a half sample of 16 babies between 3 months, 0 days and 15 months, 0 days old.

* Try to distribute participant ages across the full range of ages if possible.
    * **Please report the exact age in days.** You can use an online tool such as: [https://www.calculator.net/age-calculator.html](https://www.calculator.net/age-calculator.html)
* In situations where labs planned but were unable to collect the minimum contribution, laboratory members will still be eligible for authorship. Alternative contributions may be requested by the Leadership Team in these circumstances.
* A lab’s sample size contribution **includes any infant who enters the laboratory**, even if they are eventually excluded (e.g., due to fussiness, experimenter error, etc).

While we encourage as much participation as you can spare, it is crucial to the success of the project that you treat our study with the same care as you would any other study in your lab with respect to recruitment procedures, timing of data collection, and RAs/RA training. Please do not commit to providing data to ManyBabies if this level of care is not possible.

### Eligibility and Exclusions
**The <u>only</u> requirements for inclusion in MB5 are that an infants’ age falls within the 3- to 15-month age range and that the infant has no known issues that would directly impede their ability to process visual stimuli.** Infants who are hard of hearing, premature, bilingual, etc can be included in the lab’s sample.

Please determine participants’ eligibility on the phone prior to scheduling them in the ManyBabies study to avoid testing ineligible participants, but note that the inclusion criteria for MB5 are much more inclusive than typical in-lab studies (described above). Participants who come into the lab who are subsequently determined to be ineligible should be reported in the sample.

### First-session/second-session policy
Some laboratories have the practice of testing babies in more than one study during the same visit. ***‘First session’*** refers to babies tested soon upon arrival to the lab, prior to participating in any other studies. ***‘Second session’*** refers to any testing that is done after the first session. 
* **Please contribute ‘first session’ babies when possible.** It is possible that second session babies will contribute worse/weaker/different data with respect to the larger goals of determining effect sizes. 
* **Please label ‘second session’ babies** appropriately if infants were run in a different study on the same visit prior to their participation in MB5. Please also document the nature of the study run prior to MB5 for all ‘second session’ participants (e.g., “7 minute study of object categorization using eye-tracking”). 