# MB5 Collaboration Agreement {#sec-collaboration}

::: callout-important
# IMPORTANT! {.mark .unnumbered}

### By participating in {{< var project.name >}}, you agree to abide by the {{< var project.number >}} Collaboration Agreement. 
:::

All ManyBabies projects have a **Collaboration Agreement**, which is a document that outlines the anticipated products, roles and responsibilities, and planned authorship model for publications. This agreement is intended to provide clarity and transparency for all contributors. If you have questions about this agreement or would like to suggest an amendment, please [contact the Project Leads]({{< var email.mailto >}}). 

#### Changes to this Collaboration Agreement
As the project evolves, changes may be made to this collaboration agreement. In those instances, all collaborators will be notified of the change via project listserv and a list of recent changes will be listed at the top of the document. Contributors will have one week from the time of notice to object to changes, and all reasonable efforts will be made by Project Leads to address any concerns/objections. If such concerns/objectives cannot be resolved through discussion and/or mediation, the MB Governing Board will have final discretion. 

***
### {{< var project.name >}} Collaboration Agreement
> View the {{< var link.collaboration >}} in a browser

<iframe src="https://docs.google.com/document/d/e/2PACX-1vQsLk557N0kBYSLtx9-bvtIkIiUD8H-zY0GqN3u64cQITwK4c85Xv82n6vzZzZcIBPVGPUobeQCCeqk/pub?embedded=true" width="100%" height="650"></iframe>