# Apparatus {#sec-apparatus}

## Room Set-Up

During the experiment, infants will be seated on their caregiver’s lap or in a high-chair or car seat (whichever option corresponds to a lab's standard procedure for testing infants, as reported in the pre-data-collection survey).^[See @sec-apparatus for more detail.]


## Equipment

The minimal equipment required to run this experiment is:

-   Computer running experiment software (see below)
-   Monitor/television for stimulus display
-   Camera for capturing infant looking behavior[^3.4-apparatus-1]
-   Mixer for syncing recording of infant with stimulus timing (or other method for doing so)

[^3.4-apparatus-1]: This can be a scene view embedded in an eye tracker.

Addional (optional) equipment:

-   Eye tracker
-   Blacked-out glasses for parent to wear during experiment

::: callout-important
PUT IN GRAPHIC SHOWING APPARATUS/SET-UP
:::

## Software

We assume you will use an experimental software (e.g. Matlab, Habit, E-Prime, Psychopy, OpenSesame or custom software) to run the study and one of three settings to record looking times:

1.  Offline Video recording
2.  Eye-tracker (e.g. Tobii, EyeLink, SMI, ASL, or a different company) with appropriate software from the eye-tracker or custom software
3.  Eye-tracker + video recording.

We also assume you know how to set up looking-time studies on your equipment. If that is not the case, or if you need help, support is available from the following people:

-   PsychoPy:
-   PyHab:
-   Tobii:
-   Eyelink:
-   Other systems: email us ({{< var email.support >}}) and we’ll do our best to help out
