project:
  type: book
  output-dir: docs

reference-location: margin # footnotes in margin
link-citations: true       # citations link to references
number-depth: 2

bibliography: references.bib
csl: apa.csl

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section

language:
  crossref-ch-prefix: Chapter
  crossref-apx-prefix: Appendix

format:
  html:
    theme: cosmo
    
  pdf:
    documentclass: scrreprt
    csl: apa.csl

editor: visual

book:
  title: "Lab Manual for ManyBabies 5: Hunter & Ames Model of Infant Looking Preference"
  author: "MB5 Leads"
  date: last-modified
  repo-url: https://github.com/manybabies/mb5-manual
  sidebar:
    style: "docked"
    footer: license.qmd
  chapters:
    - index.qmd
    - part: 1-general-info.qmd
      chapters:
        - 1.1-collab-agreement.qmd
        - 1.2-contact-info.qmd
        - 1.3-test-dates.qmd
        - 1.4-lab-overview.qmd
    - part: 2-getting-started.qmd
      chapters: 
        - 2.1-green-lighting.qmd
        - 2.2-demographics.qmd
        - 2.3-objects.qmd
        - 2.4-ethics.qmd
        - 2.5-walkthrough.qmd
        - 2.6-data-validation.qmd
    - part: 3-experiment-overview.qmd
      chapters: 
        - 3.1-participants.qmd
        - 3.2-stimuli.qmd
        - 3.3-procedure.qmd
        - 3.4-apparatus.qmd
        - 3.5-prior-to-data-coll-checklist.qmd
    - part: 4-running-experiment.qmd
      chapters:
        - 4.1-general-lab-practices.qmd
        - 4.2-test-conditions.qmd
        - 4.3-during-data-collection.qmd
    - part: 5-after-data-collection.qmd
      chapters:
        - 5.1-data-reporting.qmd
    - references.qmd
  page-footer: 
    left: "ManyBabies5 Lab Manual"
    right: 
      - icon: link-45deg
        href: https://manybabies.org/MB5
      - icon: envelope
        href: mailto:mb5@manybabies.org
      - icon: github
        href: https://github.com/manybabies/mb5-analysis
      - icon: book
        href: https://doi.org/10.31234/osf.io/ck3vd



