project:
  type: book
  output-dir: docs

reference-location: margin # footnotes in margin
link-citations: true       # citations link to references
number-depth: 2

bibliography: references.bib
csl: apa.csl
reference-section-title: References

crossref:
  fig-prefix: figure
  tbl-prefix: table
  sec-prefix: section

language:
  crossref-ch-prefix: chapter
  crossref-apx-prefix: appendix

format:
  html:
    theme: cosmo
    
  pdf:
    documentclass: scrreprt
    csl: apa.csl

editor: visual

book:
  title: "Many Babies 5 Lab Manual"
  author: "MB5 Leads"
  date: last-modified
  repo-url: https://github.com/manybabies/mb5-manual
  sidebar:
    style: "docked"
    footer: license.qmd
  chapters:
    - index.qmd
    - part: "General information"
      chapters:
        - contact-info.qmd
        - test-dates.qmd
        - lab-checklist.qmd
    - part: "Getting started"
      chapters: 
        - getting-started.qmd
        - green-lighting.qmd
        - ethics.qmd
        - participants.qmd
        - general-lab-practices.qmd
    - part: "Setting up the experiment"
      chapters: 
        - setting-up-experiment.qmd
        - equipment.qmd
        - prior-to-data-coll-checklist.qmd
    - part: "Running the experiment"
      chapters:
        - during-data-collection.qmd
    - part: "After data collection"
      chapters:
        - after-data-collection.qmd
    - references.qmd
  appendices:
    - collab-agreement.qmd


