project:
  type: book
  output-dir: docs

reference-location: margin # footnotes in margin
link-citations: true       # citations link to references

book:
  title: "MB5-manual"
  author: "MB5 Leads"
  date: last-modified
  repo-url: https://github.com/manybabies/mb5-manual
  sidebar:
    style: "docked"
    footer: license.qmd
  chapters:
    - index.qmd
    - getting-started.qmd
    - setting-up-experiment.qmd
    - general-lab-practices.qmd
    - prior-to-data-coll-checklist.qmd
    - during-data-collection.qmd
    - after-data-collection.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl
reference-section-title: References

crossref:
  fig-prefix: figure
  tbl-prefix: table
  sec-prefix: section

language:
  crossref-ch-prefix: chapter
  crossref-apx-prefix: appendix

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

