project:
  type: book
  output-dir: docs

reference-location: margin # footnotes in margin
link-citations: true       # citations link to references
number-depth: 2

bibliography: references.bib
csl: apa.csl

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section

language:
  crossref-ch-prefix: Chapter
  crossref-apx-prefix: Appendix

format:
  html:
    theme: cosmo
    
  pdf:
    documentclass: scrreprt
    csl: apa.csl

editor: visual

book:
  title: "ManyBabies 5: Hunter & Ames Model of Infant Attention - Lab Manual"
  author: "MB5 Leads"
  date: last-modified
  repo-url: https://github.com/manybabies/mb5-manual
  sidebar:
    style: "docked"
    footer: license.qmd
  chapters:
    - index.qmd
    - part: general-info.qmd
      chapters:
        - contact-info.qmd
        - test-dates.qmd
        - lab-overview.qmd
    - part: getting-started.qmd
      chapters: 
        - green-lighting.qmd
        - demographics.qmd
        - ethics.qmd
        - walkthrough.qmd
        - data-validation.qmd
    - part: experiment-overview.qmd
      chapters: 
        - participants.qmd
        - stimuli.qmd
        - procedure.qmd
        - apparatus.qmd
        - prior-to-data-coll-checklist.qmd
    - part: running-experiment.qmd
      chapters:
        - general-lab-practices.qmd
        - test-conditions.qmd
        - during-data-collection.qmd
    - part: after-data-collection.qmd
      chapters:
        - data-reporting.qmd
    - references.qmd
  appendices:
    - collab-agreement.qmd
  page-footer: 
    left: "ManyBabies5 Lab Manual"
    right: 
      - icon: link-45deg
        href: https://manybabies.org/MB5
      - icon: envelope
        href: mailto:mb5@manybabies.org
      - icon: github
        href: https://github.com/manybabies/mb5-analysis
      - icon: book
        href: https://doi.org/10.31234/osf.io/ck3vd



