project:
  type: book
  output-dir: docs

reference-location: margin # footnotes in margin
link-citations: true       # citations link to references
number-depth: 2

book:
  title: "Many Babies 5 Lab Manual"
  author: "MB5 Leads"
  date: last-modified
  repo-url: https://github.com/manybabies/mb5-manual
  sidebar:
    style: "docked"
    footer: license.qmd
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - contact-info.qmd
        - test-dates.qmd
        - lab-checklist.qmd
    - part: getting-started.qmd
      chapters: 
        - green-lighting.qmd
        - ethics.qmd
        - participants.qmd
    - part: setting-up-experiment.qmd
      chapters: 
        - equipment.qmd
    - general-lab-practices.qmd
    - prior-to-data-coll-checklist.qmd
    - during-data-collection.qmd
    - after-data-collection.qmd
    - references.qmd
  appendices:
    - collab-agreement.qmd


bibliography: references.bib
csl: apa.csl
reference-section-title: References

crossref:
  fig-prefix: figure
  tbl-prefix: table
  sec-prefix: section

language:
  crossref-ch-prefix: chapter
  crossref-apx-prefix: appendix

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

