# Apparatus {#sec-apparatus}

## Room Set-Up

During the experiment, infants will be seated on their caregiver’s lap or in a high-chair or car seat[^apparatus-1] in front of a screen. The optimal distance between the infant and the screen will depend on the size of the screen, and labs should use their normal testing set-up (if applicable).

[^apparatus-1]: Whichever option corresponds to a lab's standard procedure for testing infants, as reported in the pre-data-collection survey

For labs unaccustomed to testing infants in a procedure like this, you can use a visual angle calculator to determine an optimal distance from the screen[^apparatus-2].

[^apparatus-2]: Please {{< var email.emailus >}} if you need guidance.

::: callout-caution
ADD IN VISUAL ANGLE CALCULATOR INSTRUCTIONS
:::

We encourage labs to follow their normal procedure for ensuring that parents do not influence their infant's behavior during the experiment. This can include asking parents to wear blacked-out sunglasses, close their eyes, or look down at the infant (and not at the screen).

Stimlui will be presented on the screen according to the specifications in @sec-procedure.

## Equipment

#### The minimal equipment required to run this experiment is:

-   Computer running experiment software (see below)
-   Monitor/television for stimulus display (with audio capability to play music/attention-getter sounds)[^apparatus-3]
-   Camera for capturing infant looking behavior[^apparatus-4]
-   Mixer for syncing recording of infant looking with stimulus timing (or other method for doing so)

[^apparatus-3]: Can be a laptop screen, if needed (a large external screen is preferable)

[^apparatus-4]: This can be a scene view embedded in an eye tracker, or a webcam from a laptop.

#### Addional (optional) equipment:

-   Eye tracker
-   Blacked-out glasses for parent to wear during experiment

::: callout-caution
PUT IN GRAPHIC SHOWING APPARATUS/SET-UP
:::

## Software

To maximize accuracy, we encourage labs to use one of the following supported hardware/software options to run the experiment:

-   **Eyetracking (Eyelink):** Experiment Builder *[IN DEVELOPMENT, est. release date: early August 2026]*
-   **Eyetracking (Tobii):** PsychoPy *[IN DEVELOPMENT, est. release date: early August 2026]*
-   **Offline coding:** <a href="https://drive.google.com/drive/folders/18MByu_o8v1WKOEly_snZJlt8-Ip8xtYG?usp=drive_link" target="_blank">PsychoPy</a> *(<a href="https://docs.google.com/document/d/1nxaWc40bQQCJFkOsAn3B-46irecrmignpF-HhiVqKWM/edit?usp=drive_link" target="_blank">manual</a>)*

Click on the software option you would like to use to access experiment and set-up order files. Let us know as soon as possible if you plan to use an alternative experiment program version not listed above.

### Order files

Each experiment package linked above includes one SET-UP ONLY trial list that your lab should use to set up the experiment and collect pilot/dummy data for green-lighting purposes. As discussed in @sec-orders, each lab will be provided with a custom set of trial orders to use for testing actual participants when that lab has been given a "Green-Light" for tetsing.



::: callout-important
# TECH SUPPORT 
#### We encourage you to check the <a href="https://airtable.com/appRoqMKzcK3NsXt4/shr1IgPxsHgYfuyIJ/tbl8ERsO85K9HEgrb" target="_blank">MB5 Issue Tracker table</a> and the {{< var link.slack-data >}} channel in the [MB Slack workspace](https://join.slack.com/t/manybabies/shared_invite/zt-3hv85sl5d-JWzJYourJw8kCttK46l~kw){target='_blank'} to see if other labs have experienced the same issue and if there is a solution provided.

## > To get help with experiment set-up issues or to report technical issues to Project Leads, please use the {{< var link.issue >}} {.unnumbered}

## > To discuss issues and crowdsource support from fellow data-collecting labs, post about your issue in the {{< var link.slack-data >}} Slack channel {.unnumbered}

#### Please be as detailed as possible in your request so that we can help you solve your issue!
:::
