# MB5 Collaboration Agreement {#sec-collaboration}

<br>


This agreement describes how work on the {{< var link.mb5dotorg >}} project will be structured and credited. The purpose of this agreement is to clarify contributor roles and expectations in the interest of transparency.

## Conduct {.unnumbered}

**Each contributor is personally accountable for the accuracy and integrity of their work on this project.** This includes ensuring that (1) you are operating in accordance with your local research rules and regulations and global norms of research ethics (e.g., [Declaration of Helsinki](https://www.wma.net/policies-post/wma-declaration-of-helsinki-ethical-principles-for-medical-research-involving-human-subjects/)), (2) you abide by the [MB Code of Conduct](https://manybabies.org/codeofconduct/) and this Collaboration Agreement at all times during your participation, (3) your specific research products are honest and accurate (e.g., data, translations, code), and (4) your description of your role on the project is accurate. **Contributors should indicate their agreement to the Code of Conduct and Collaboration Agreement by completing the MB CRediT Self-Report Form at the onset of their project participation** (see Authorship section below for more details).

All projects should comply with the [ManyBabies Code of Conduct](https://manybabies.org/codeofconduct/). Project Leads are responsible for ensuring that all project contributors have read and agreed to comply with the Code of Conduct and this Collaboration Agreement before initiating involvement in the project.

## Anticipated products {.unnumbered}

We anticipate that this project will result in:

1.  A paper to be preprinted at [PsyArXiv](https://psyarxiv.com) and submitted to the journal *Nature Human Behaviour*
2.  Multiple conference presentations
3.  Stimuli, experiment software, and an experiment protocol to be shared on Open Science Framework ([OSF](https://osf.io/)) for reuse after the preprint is published
4.  Raw video data (from labs with permission to share and parental consent), to be shared on [Databrary](https://nyu.databrary.org/) and indexed with the label "ManyBabies5"
5.  Looking-time data, to be shared via [GitHub](https://pages.github.com/) and/or OSF
6.  Participant information (de-identified), such as age and language exposure, to be shared via GitHub and/or OSF
7.  Analysis code, to be shared via GitHub and/or OSF

These anticipated products might change/evolve over the course of the project and are meant to serve as an expected set of products rather than an exhaustive list. Contributors will be notified of any updates or changes to anticipated products via the project listserv.

## Roles and responsibilities {.unnumbered}

**All project contributors are expected to abide by this Collaboration Agreement regardless of contribution role, and to self-report contributions accurately using the [MB Contribution Reporting form](manybabies.org/credit)**. We welcome individuals making contributions in more than one domain, and note that **data collection is not a required contribution for authorship** (see Authorship section for more information). Please make sure that you report any changes to your role in a timely manner to ensure that you get proper credit for all of your contributions.

Below is information about specific project roles and their respective responsibilities.

### Project Leads

-   Formulating the research goals and aims
-   Providing repeated opportunities for scholars of any career stage to contribute to the project
-   Creating, maintaining, and sharing project-specific documentation (Collaboration Agreement, Lab Manual, etc.)
-   Organizing project-specific information on OSF, Google Drive, GitHub, etc.
-   Documenting project progress from beginning to end, including timely website and newsletter updates
-   Coordinating the work of all other teams via regular meetings and check-ins
-   Ensuring that MB policies are followed
-   Coordinating the organization of lab IRB ethics approval documents
-   Actively answering project-related questions
-   Supporting exchanges on Slack or other communications platform that aids project administration (e.g. ensuring that questions about procedure and setup are answered)
-   Coordinating manuscript submission and pre-print services
-   Ensuring that all study materials (e.g., stimuli, analysis code, anonymized data) are properly archived and publicly accessible at the earliest possible stage, and at the time of publication at the latest

### Methodology Team

-   Developing study materials (e.g., stimuli, experiment files, questionnaires) and procedure(s)
-   Providing all scripts used during stimulus creation, and exhaustively documenting all reasoning behind stimulus creation and selection decisions
-   Leading the coordination of materials translation and adaptation as needed
-   Providing clear instructions on how to set up the study for participating labs
    -   These instructions should be publicly available at the time of publication and allow for a direct replication
-   Troubleshooting methodology issues as needed
-   Contributing to the Method section of the manuscript
-   Reviewing and (if desired) providing feedback on the remainder of the original and revised manuscript
-   Maintaining regular communication with the Project Leads

### Data Collection Teams

***\*Note: The expectation is that each data-collecting laboratory will be represented in authorship by*** <u>one or two</u> researchers (e.g., a lab PI who oversees data collection, and a student or RA who is primarily responsible for data collection). Requests to include more than two researchers from a lab must be approved by Project Leads.

-   Obtaining and documenting ethics approval for data collection, as locally appropriate
-   Creating and sharing a short “walkthrough video” of lab set-up and testing procedure, as appropriate
-   Ensuring that all ManyBabies and project-specific data collection guidelines (e.g., collecting data from the agreed-upon number of participants, following stopping rules, submitting data from any infant who enters the lab) are followed
-   Ensuring all ethical practices (e.g. properly obtaining consent, anonymizing data as needed, etc.) are followed
-   Making reasonable efforts to check and ensure data quality (e.g., checking manual data entry, documenting issues reported by research assistants and participants)
-   Following data formatting guidelines and confirming correct formatting by using the [MB Data Validator](manybabies.org/validator) prior to submission
-   Documenting and reporting issues to the Project Leads
-   Assisting with materials translations
-   Responding efficiently to project-related correspondence
-   Reviewing and (if desired) providing feedback on the original and revised manuscript
-   Ensuring all authors on the team maintain an active email contact on the project mailing list until the project is fully complete (normally the time that the peer-reviewed manuscript proofs have been finalized)

### Data Analysis Team

-   Setting up the data validator and creating a data template for data collection teams
-   Specifying in detail the confirmatory analyses for Stage 1 submission, together with analysis code, and (where possible) analyzing pilot data to illustrate its appropriateness
-   Conducting a power analysis to estimate the required sample size prior to the Registered Report submission
-   Analyzing data and (in collaboration with Project Leads) coordinating external code review, and (normally) writing the Results section of the peer-reviewed manuscript.
-   Sharing analysis code (with clear comments) publicly via GitHub or a similar service (linked to OSF)
-   Ensuring that shared data are fully anonymized prior to public release
-   Contributing to the Analysis Plan section of the Registered Report and the Results section of the Stage 2 manuscript
-   Reviewing and (if desired) providing feedback on the remainder of the original and revised manuscript
-   Maintaining regular communication with the Project Leads

### Writing Team

-   Writing the original manuscript draft, in consultation and collaboration with the Methodology and Data Analysis Teams
-   Soliciting feedback on manuscript drafts and reviewer comments from the full project team
-   Incorporating feedback and developing a revised manuscript draft
-   Maintaining regular communication with the Project Leads

## Authorship {.unnumbered}

#### How do I become an author on a paper that results from this project?

All project contributions will be documented via an adaptation of the [CRediT taxonomy](https://credit.niso.org/) using an authorship spreadsheet generated from the project’s [MB Contribution Reporting Form](manybabies.org/credit). All authors, regardless of whether they are part of the writing team, must review the final manuscript and will be given the opportunity to provide feedback prior to submission. In addition, all authors must make a substantive contribution to at least one of the roles outlined above and report their contribution(s) via the corresponding MB CRediT category(s).

If you contribute to the project in the manner outlined above, you are eligible for authorship. Contributions will be compiled in the [MB CRediT table](https://manybabies.org/credit/) and this information will be appended to (or referenced in) all relevant scientific products (e.g., manuscript) in accordance with journal guidelines.

In general (and except in very limited circumstances), authors will not be added to a manuscript (e.g., Stage 1 Registered Report) between the first submission to a journal and subsequent revisions. In the case that a change to authorship is deemed appropriate by Project Leads, all authors will be notified of the proposed change via project listserv and be given at least one week to object to the change. Depending on the policies of the journal, authorship changes will be (1) approved on behalf of the consortium by the corresponding author (preferred) or, (2) approved by each author individually.

\[**Note:** Given the nature of MB projects, it is likely that many (if not most) authors will contribute to the project as a member of a data collection team only (corresponding to the “Investigation” CRediT category). For all authors, including those who plan to collect data, authorship on Stage 1 manuscripts will be based on **planned** contributions and authorship on Stage 2 manuscripts will be based on **actual** contributions. It is expected that authors will join the project in response to a call for data collectors after the Stage 1 manuscript has been accepted.\]

#### How do we handle dissenting opinions about scientific products?

In large-scale collaborations, disagreements are inevitable. Whenever possible, decisions will be made using a consensus-based decision-making process. Project Leads are expected to carefully consider dissenting opinions from collaborators and, to whatever extent is reasonable, discuss the issue with the dissenter and with all active team members/contributors when appropriate. In some cases, decision-making may default to democratic voting; however, this will not always be deemed the best approach. Where consensus can’t be reached, final decisions about the scientific product will ultimately be left to the Project Leads.

#### How will authorship order be determined?

Authorship order will be organized into the following sections, with order determined as listed below:

*Section 1 (First Author(s)):* Main proposer(s) (as determined by consensus of Project Leads) listed first, ordered based on contribution, followed by remaining Project Leads, ordered reverse alphabetically.

*Section 2 (Team Leads/Other Significant Contributors):* Leaders of working groups (e.g., methods, analysis, writing) and others who have made significant/leading contributions (as determined by Project Leads), ordered reverse alphabetically.

*Section 3 (Other Contributors):* Remaining project contributors not specified in other sections, ordered reverse alphabetically.

*Section 4 (Senior Authorship):* Project Leads designated as senior authors (as determined by consensus of Project Leads), ordered in reverse based on contributions.

\[**Note:** A note describing this ordering procedure will be added to the author notes\]

#### How do we handle authorship on secondary papers for this project?

\[For comprehensive information on ManyBabies policy regarding secondary projects, please see the section “Policies on Derived Projects and Presentations” in the [MB General Manual](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit#heading=h.wxrfm5m3ma0l).\]

It is possible that this project results in secondary papers that are based on the project’s research products. Prior to the full public release of the main project, secondary papers should only be initiated with the consent of the Project Leads. After full public release, projects may be freely initiated without any special permissions from the Project Leads. The only exception to these rules are projects with a primarily pedagogical purpose (for example, undergraduate or Master’s theses). These may be initiated at any time without any special permissions from the Project Leads, as long as the written reports based on these projects are not disseminated publicly before the full public release of the main project. If you are working on an educational project and your institution requires posting your thesis to a public repository (such as a library repository), contact the Project Leads for guidance.

All secondary projects should be governed by their own collaboration agreement. By default, authors on the main paper will not be counted as authors on secondary papers unless they also become involved in the work of these secondary projects. All secondary papers should cite the primary written public report of the main project.

All secondary projects involving ManyBabies collaborators should be announced to the Project Leads and all outputs of secondary projects should be reported to ManyBabies via the [activity and initiative tracking form](https://docs.google.com/forms/d/e/1FAIpQLSd_3MDyUaDY4xKELqd4-Ugkz1r3kigbJdg8yTPQieFsG58bJw/viewform).

#### How do we handle the use of project materials/data for other derived projects and presentations?

All other uses of project materials and/or data (e.g., for department or conference presentations) are subject to ManyBabies’ policies on derived projects and presentations. Please refer to this section in the [MB General Manual](https://docs.google.com/document/d/1dZ3sF2UcxvpkfOfKSKFeObTMZRbpUYloMUiPYtZy0ng/edit#heading=h.wxrfm5m3ma0l) for more information, and direct all questions to Project Leads and/or the MB Executive Director ([contact\@manybabies.org](mailto:contact@manybabies.org))

## Press and public reporting of ManyBabies results {.unnumbered}

Initial press releases will be coordinated by the Project Leads and ManyBabies leadership once the paper is accepted or at any time point the leads deem suitable for wider dissemination. All press releases must (a) prominently highlight the role of the MB collaborative network, and (b) link to MB contacts. All collaborators are encouraged to speak to the press, but are expected to (1) emphasize the highly-collaborative nature of the research project and (2) encourage the interviewer to reach out to various members of the team. The content of the press release and paper is embargoed until the time and date clearly stated on the press release.

## Changes to this Collaboration Agreement {.unnumbered}

As the project evolves, changes may be made to this collaboration agreement. In those instances, all collaborators will be notified of the change via project listserv and a list of recent changes will be listed at the top of the document. Contributors will have one week from the time of notice to object to changes, and all reasonable efforts will be made by Project Leads to address any concerns/objections. If such concerns/objectives cannot be resolved through discussion and/or mediation, the Governing Board will have final discretion.

## Contact info {.unnumbered}

We encourage you to ask questions and raise concerns about project-related matters as soon as possible. You can direct all questions and concerns to [jkosie\@asu.edu](mailto:jkosie@asu.edu), [mzettersten\@ucsd.edu](mailto:mzettersten@ucsd.edu), and/or [caseylw\@princeton.edu](mailto:caseylw@princeton.edu). If you have an issue or concern that you would like addressed by MB leadership, you can contact the [MB Executive Director](mailto:contact@manybabies.org) or the [MB Governing Board](mailto:govboard@manybabies.org).

------------------------------------------------------------------------

-   *Authored by:* ManyBabies (adapted from the Psychological Science Accelerator Collaboration Agreement template)
-   *Amended by:* Jessica Kosie, Martin Zettersten, Christina Bergmann, Dima Amso, Casey Lew-Williams
-   *Reviewed by:* J.K., M.Z., C.L.-W., Heidi Baumgartner
-   *Date updated:* 2022-04-29
