# Data Dictionary and Templates {#sec-datatemplates}

## Data overview

The primary deliverables for the project are two data files:

-   **Participant data**: 1 row per participant
-   **Trial data**: 3 rows per trial (*familiarization*, *test1*, and *test2*) per participant (36 rows/participant)

In addition, labs are asked to submit DE-IDENTIFIED raw data. For labs using eye trackers, this is raw gaze data (either as a single file or 1 file/participant), and for labs not using eye trackers, this is the output file generated by PsychoPy or another software program with stimulus and key press timing information.

## MB5 Data Dictionary

The MB5 Data Dictionary lists all of the variables that should be included in the Participant Data and Trial Data files. Each row contains a variable and that variable’s specified format (e.g., string, integer), set of example values, and description. It is important that your lab’s data follows these specifications exactly in order to allow for data harmonization with the full dataset.

::: callout-important
The MB5 Data Dictionary is under development.
:::

## MB5 Data templates

::: callout-caution
# IMPORTANT NOTE #1 {.mark .unnumbered}

These two files must use **identical, anonymous subject identifiers (`participant_id`)**. We must be able to link participant- and trial-level data across files! You can use your lab’s normal participant numbering convention (e.g., 001, 002, 003, etc.), as long as **`participant_ID` DOES NOT include any private information** (e.g., initials, birth date).
:::

::: callout-caution
# IMPORTANT NOTE #2 {.mark .unnumbered}

These files must contain **de-identified data ONLY**. All potentially identifying information should be stripped from your data file before submission. For example, you SHOULD NOT include birth date and test date in your Participant Data file. Instead, use an age calculating tool (e.g., https://www.calculator.net/age-calculator.html) to calculate each participant’s age in days, and report that value in the `age_days` variable. In addition, `participant_id` numbers SHOULD NOT contain any personal information (e.g., name, birthdate, initials) and should instead be completely de-identified (e.g., mb5_01, mb5_02, etc.). If you have any questions about ensuring your data is de-identified, {{< var email.emailus >}}.
:::

::: callout-caution
# IMPORTANT NOTE #3 {.mark .unnumbered}

It’s really important to remember that these files are designed to be read by a computer program, not a person. So anything that violates the template (e.g., variables that aren’t of the specified type, formatting, comments, etc.) will not work. For example, cells in the column `lang1_exposure` in the participant data file should contain numbers. If you write "80 to 90" this will cause errors because it contains characters in addition to numbers *(note: please check questionnaire responses before participants leave the lab to avoid NA responses)*. If you have questions, comments, or calculations, please communicate directly with the analysis team, rather than embedding them in the data.
:::

::: callout-caution
# IMPORTANT NOTE #4 {.mark .unnumbered}

Please **do not leave any fields blank**. If something does not logically have an answer, or if you did not collect this information, please mark it as “NA”.
:::

Please download a copy of each template and use them as guides for formatting your lab’s data.

Files must be in CSV (comma separated values) format. PLEASE NOTE that saving in this format will remove any formulas or other non-plain-text features of your spreadsheet (e.g,. color fills, formatting); all information should be captured in the text within each cell.

### Participant Data

A .csv file with one row for each participant, and with columns showing participant-level variables (e.g., `participant_id`, age, demographic information, notes on the session, etc.)

::: callout-important
Participant Data template is under development.
:::

### Trial Data

A .csv file with three rows for each trial, and with columns showing `participant_id`, and trial and trial-phase level variables (e.g., trial number, trial type (*simple*, *complex*), trial phase (*familiarization*, *test1*, *test2*) looking time, etc.)

::: callout-important
Trial Data template is under development.
:::
