# Demographics questionnaire {#sec-demographics}

## Collecting participant information

**Please use an appropriate version of the {{< var project.number >}} Demographics Questionnaire**[^demographics-1] to collect information about participants and their families/caregivers.

[^demographics-1]: See below for more information on adapting/translating the template

### \>\> [MB5 Demographics Questionnaire directory]({{< var url.demographics >}}) \<\<

> Please refer to the "README" file in this directory for more information on using/translating/adapting templates.

<br>

This questionnaire is adapted from the template(s) created by the <a href="https://manybabies.org/MB-Demographics/" target="_blank">MB-Demographics</a> group.[^demographics-2] As noted in @Singh2024, the MB Demographics Questionnaire template was developed to **query information pertaining to six constructs** (*biographical information*, *gestational status*, *health status*, *community of descent*, *caregiving environment*, and *socioeconomic status*). We have added a few additional questions that are of particular interest to MB5 (e.g., family history of colorblindness) to create the {{< var project.number >}} Demographics Questionnaire template.

[^demographics-2]: See @Singh2024 for more information on the development of the template

::: callout-warning
# CHECK FOR MISSING DATA

While parents/guardians can choose to not respond to individual questions, please **CHECK THE FORM BEFORE THE RESPONDANT LEAVES YOUR LAB** to avoid accidental blank responses/missing data.[^demographics-3]
:::

[^demographics-3]: In other words, please confirm that blank items are **intentional non-responses** rather than mistakes (e.g., respondent didn't understand what the question was asking, didn't know the questionnaire form continued on the next page, etc.).

## Adaptations and translations

We have created an English-language version template that is suited for a United States context. If you are collecting data in a language other than English, please do your best to translate the questionnaire so that you are querying the same *construct* as the template item. 

::: callout-note
# MB5 Demographics Questionnaire directory
Translations/adaptations of the MB5 Demographics Questionnaire will be available [**here**]({{< var url.demographics >}}){target="_blank"} as they become available.[^demographics-4] 

> We are unable to centrally verify the accuracy of all translations/adaptations. Labs are responsible for reviewing adaptations to ensure that they are appropriate for their context and query the constructs in the original template (`mb5_demographics-questionnaire_english-US-template`). Labs are encouraged to work with others in their geographic region to create context-appropriate versions of the questionnaire.
:::

[^demographics-4]: Existing translations/adaptations of the original MB-Demographics template are available via the <a href="https://osf.io/nqc92/files/osfstorage" target="_blank">MB-Demographics OSF repository</a>.

#### We recognize that the specific questions/response options in the example template (which was developed in English for use in the United States) are not appropriate for all contexts.

We encourage labs to translate and adapt the questionnaire template as needed, while keeping in mind the **goal of querying the same constructs included in the original template to ensure consistency in reporting**. For example, the question on race/ethnicity can be adapted to meet the norms of your region. If possible, please use racial/ethnic categories taken from local census categories. For countries where it is not considered socially or legally acceptable to inquire about ethnic background, please adapt to a more appropriate question (e.g., parent and child place of birth), if possible.

If you have any questions about adapting the questionnaire, please {{< var email.emailus >}} to discuss your concerns. Let us know if any of the questions are unclear to you---it is important that you are able to answer any questions parents/guardians may have.

## Uploading demographics questionnaire

**All labs must upload a blank copy of the Demographics Questionnaire they will be using for MB5** via the [**MB5 Upload Form**]({{< var url.upload >}}){target="_blank"} *(even if you are using the provided template with no modifications!)*.

Please ensure that all uploaded materials are clearly labeled in the filename with your LabID (e.g. `babylabPrinceton_questionnaire.pdf`). Check the list of {{< var link.labids >}} to confirm your lab's unique LabID before uploading.
