# Equipment and software

## Equipment
The minimal equipment required to run this experiment is:

* Computer running experiment software (see below)
* Monitor/television for stimulus display 
* Camera for capturing infant looking behavior^[not needed if infant's face is captured by eye-tracker] 



## Software
We assume you will use an experimental software (e.g. Matlab, Habit, E-Prime, Psychopy, OpenSesame or custom software) to run the study and one of two settings to record looking times: (1) Offline Video recording (2) Eye-tracker (e.g. Tobii, EyeLink, SMI, ASL, or a different company, with appropriate software from the eye-tracker or custom software). (3) Eye-tracker + video recording. We also assume you know how to set up looking-time studies on your equipment. If that is not the case, or if you need help, support is available from the following people: 

* PsychoPy: 
* PyHab: 
* Tobii: 
* Eyelink: 
* Other systems: email us [mb5@manybabies.org](mailto:mb5@manybabies.org) and we’ll do our best to help out