# Ethics approval {#ethics-approval}

## Overview
All data-collecting labs are required to obtain ethics approval from their local oversight board (e.g., IRB)[^ethics-1]. As this process can take time, it is a good idea to **get started on your ethics approval application as soon as possible**. Approvals must be in place and a copy submitted via the process described below before you can obtain a green light to collect data. [Contact us](mailto:mb5@manybabies.org) if you need advice or help with obtaining ethics approval.

[^ethics-1]: If your lab/institution does not have a formal ethics oversight board, please refer to [MB's general ethics guidance](https://docs.google.com/document/d/e/2PACX-1vR2nv4Wy1soDS4cBBNy9QZOyewvvjP1ka1reBRhAIzcrNi0reJxgHuhGS7f7i2wE0ScQuppek8Al_21/pub) and contact the Project Leads to confirm ethics compliance

> In some cases, labs will already have approval for MB5 under an “umbrella protocol” (i.e., a protocol that covers multiple studies in one lab). In these cases, the ethics form should still be uploaded as described below.


## Permission to collect/share demographic data

MB5 (and other ManyBabies projects) ask labs to collect a number of demographic background variables (e.g., gestational age, sex, parental education, community of descent) to be shared along with the main data (after full de-identification is confirmed) (see [**Demographics questionnaire**](ADD%20LINK%20TO%20DEMOGRAPHICS%20QUESTIONNAIRE) for all items). Not all of those variables are part of the main analysis. Even so, it is highly relevant to collect them for describing our sample, for follow-up and secondary analyses, and for checking the representativeness of the sample.

##### Please make sure you have permission to publicly share anonymized raw data (including required demographic info), as this is a condition of participation. {.unnumbered}

Contact us [**mb5\@manybabies.org**](mailto:mb5@manybabies.org) if your ethics board raises concerns about collecting and/or sharing these data.

## Permission to share video recordings

We strongly encourage labs (where possible) to store and share video recordings of their testing sessions on [**Databrary**](https://nyu.databrary.org/), which is a secure site created for this purpose. Databrary allows for different levels of privacy: fully private (available only to the uploading research group), shared only with Databrary-approved researchers, or fully open. **You will need to ensure that you have ethics approval in place to upload and/or share recordings, and collect specific consent for this purpose from your participants' parents/guardians.** In addition, you will need to become a member of Databrary, which requires approval from your institution, so it’s helpful to start this process early. You can [begin the registration process for Databrary here](https://nyu.databrary.org/user/register?page=create). We are aware that many laboratories, particularly those based in the European Union, may not be allowed to use Databrary. In these circumstances we encourage labs to use alternative methods for sharing their videos where possible.

## Uploading ethics approval documentation {#ethics-upload}

Ethics documentation (e.g., proof of IRB approval) must be submitted to the MB5 leads prior to data collection. Submit your lab's ethics approval documentation using the [**MB5 documentation upload form**](https://docs.google.com/forms/d/e/1FAIpQLScunCYwrJApObng6xVV_lN4CUrcLrsrAKmiBmia67vPc9jNTA/viewform?usp=sf_link).

**Please ensure that all uploaded materials are clearly labeled in the filename with your LabID (e.g. *babylabPrinceton_ethics.pdf*).** Check the [**list of LabIDs**](https://manybabies.org/labids/) to confirm your lab's unique LabID before uploading.
