# Green-Lighting process overview {#sec-greenlight}

All labs must complete a series of preparation steps, referred to by ManyBabies as the **"Green-Lighting" process**, before collecting data for any MB project. These steps are outlined in the [{{< var project.number >}} lab participation overview](#sec-laboverview) list and explained in detail throughout the following sections of this manual, but in essence this involves:

-   providing **required documentation** (e.g., ethics approval, lab-specific Demographics Questionnaire)
-   demonstrating **correct implementation of the testing procedure**
-   successfully running pilot data through the **MB Data Validator**
-   filling out the {{< var link.pretest >}} to provide lab-level info

::: callout-important
# IMPORTANT: {.unnumbered}

## 🚫 <u>DO NOT</u> collect experimental data for {{< var project.number >}} until your lab has completed this process and received a "Green-Light" from the {{< var project.number >}} Project Leads! 🚫 {.unnumbered}

### Check the {{< var link.tracker >}} to view your lab's status
#### DO NOT begin testing unless your lab's status is <code style="background-color:#9BE095; color:black; border-radius: 20px">Green-Light for data collection</code>

:::
