# Object Familiarity questionnaire {#sec-objects}

<br> Although the visual stimuli for this study are completely novel, we would like to get a measure of if infants have any experience with objects similar to the *ManyFractals* and *ManyFribbles* used in the experiment.

**Please use an appropriate version of the** {{< var project.number >}} **Object Experience Questionnaire** to collect information about participants' experience with objects similar to the visual stimuli used in the study.

::: callout-warning
# CHECK FOR MISSING DATA

Just like the Demographics Questionnaire, please **CHECK THE FORM BEFORE THE RESPONDANT LEAVES YOUR LAB** to avoid accidental blank responses/missing data. While parents/guardians can choose not to answer any item, we want to make sure items are not left blank by mistake.
:::

## Adaptations and translations

We have created an English-language version of the Object Experience Questionnaire (`mb5_obj-exp-questionnaire_english`). If you are collecting data in a language other than English, please do your best to translate the questionnaire so that you are querying the same *constructs* as the template.

::: callout-note
# MB5 Object Experience directory

Translations/adaptations of the {{< var project.number >}} Object Experience Questionnaire will be available in the Object Experience Questionnaire Directory (below) as they become available.

> We are unable to centrally verify the accuracy of all translations/adaptations. Labs are responsible for reviewing adaptations to ensure that they are appropriate for their context and query the constructs in the original template. Labs are encouraged to work with others in their geographic region to create a context-appropriate version of the questionnaire.
:::

If you have any questions about translating the questionnaire, please {{< var email.emailus >}} to discuss your concerns. Let us know if any of the questions are unclear to you---it is important that you are able to answer any questions parents/guardians may have.

## [MB5 Object Experience Questionnaire Directory]({{< var url.obj-exp >}}){target="_blank"}

> We have provided the template (`mb5_obj-exp-questionnaire_english`) as a document and as a Google form.

## Uploading the Object Experience Questionnaire

**If you make any changes to the provided template, please upload a blank copy of the Object Experience Questionnaire your lab will be using** via the {{< var link.greenlight >}}. *(If you do not upload a version of the questionnaire, we will assume you are using `mb5_obj-exp-questionnaire_english`)*.

Please ensure that all uploaded materials are clearly labeled in the filename with your LabID (e.g. `mb5_babylabPrinceton_obj-exp-questionnaire.pdf`). Check the list of {{< var link.labids >}} to confirm your lab's unique LabID before uploading.
