# "Prior to Data Collection" checklist {#sec-prior-checklist}

The steps for getting a "Green-Light" to collect data are tracked by the MB5 Project Leads on the {{< var link.tracker >}}. You can check the tracker to see what steps your lab has completed. If you have any questions or think your lab’s progress is not up-to-date, {{< var email.emailus >}}.

As a reminder, **BEFORE BEGINNING DATA COLLECTION** your lab needs to:

-   Complete the {{< var link.signup >}} if your lab has not already done so
    -   *NOTE: if your lab does not appear in the* {{< var link.tracker >}}*, you still need to do this!*
-   Confirm demographics form is uploaded (see @sec-demographics)
-   Confirm ethics approval is uploaded (see @sec-ethics)
-   Confirm walkthrough video is uploaded (see @sec-walkthrough)
-   Validate dummy or pilot data using the {{< var link.validator >}} and upload validated data using the {{< var link.greenlight >}}
-   Complete the Pre-Test Questionnaire (COMING SOON!) to let us know that you are ready for "Geen-Lighting"

::: callout-important
# DO NOT BEGIN TESTING UNTIL YOU HAVE BEEN GIVEN A "GREEN-LIGHT"!

## Wait until you receive an official "Green-Light" from Project Leads before you begin testing! {.unnumbered}

If your lab's status in the {{< var link.tracker >}} is not `Green-Light for testing` then you have NOT been approved to begin collecting data and your data will not be included in the analyses/publication.

We may have questions for you (e.g., about any planned protocol deviations). We will do our best to respond quickly, but if you don’t hear from us within a week of submitting the Pre-Test Questionnaire, please {{< var email.emailus >}} again!
:::
