# Procedure {#procedure}

> Please adhere to the following specifications for conducting this study. If any of the following technical specifications are not possible for your lab, please contact the MB5 leadership team ([mb5\@manybabies.org](mailto:mb5@manybabies.org)) before beginning data collection to inform us of your planned deviation and the reason for it.

## Trial Structure

There are a total of 12 trials for each infant. Each trial will include both familiarization and test phases (described in further detail below). Between each trial, a "laughing baby" attention-getter will be presented.

## Overview

During the experiment, infants will be seated on their caregiver’s lap or in a high-chair or car seat (whichever option corresponds to a lab's standard procedures for testing infants, as reported in the pre-data-collection survey). Each trial is made up of a familiarization phase, in which infants are first exposed to a stimulus, followed by two test phases where infants are presented with both the item they viewed during the familiarization phase (the familiar item) and a novel test item. These phases will be repeated on each of 12 total trials.

![This figure depicts the design of an example trial. At familiarization, a single image is shown for 5, 10, or 15 s. After the desired familiarization time is reached (based on the infant-controlled or fixed-length design criteria), infants are presented with a central fixation stimulus for 500 ms. During the two test phases (5 s each), infants view the same image to which they were familiarized paired with a new stimulus from the same set (e.g., Fribbuli or Fractals) and the same level of complexity. The side on which the familiar and novel images are presented is counterbalanced across test phases, but the images remain the same.](images/mb5-trial.png){#fig-trial}

## Familiarization Phase

There are a total of 12 familiarization events for each infant that vary across three dimensions (see @tbl-familiarization):

1. Stimulus class (Fribbuli or Fractals)
2. Complexity level (low or high); and
3. Familiarization time (5s, 10s, or 15s)[^fam-1]

[^fam-1]: Familiarization can be achieved either by ending the familiarization phase of an experiment after infants have acquired a certain amount of looking at the target (i.e., an *infant-controlled* design), or by presenting the familiarization phase for a fixed amount of exposure (i.e., a *fixed-length* design).

### Infant-Controlled Familiarization[^fam-2]

[^fam-2]: Participating labs are encouraged to use an infant-controlled procedure, if possible.

If you are running the infant-controlled version of the study, infants may accumulate the required familiarization time across multiple looks before advancing to the test phase. The familiarlization image will remain on the screen until the infant has reached the target familiarization time (as determined by an experiment coding infant looking).

We will additionally implement a maximum trial length criterion; if infants do not accumulate the required looking time within twice the target familiarization time (i.e., 10, 20, or 30s), the familiarization phase will end. 

### Fixed-Length Familiarization

If you are unable to collect infant-controlled accumulated looking for familiarization trials, then you will present the familiarization trials for a fixed length of time before advancing to the test trial.

<br>

| Stimulus Class | Complexity Level | Familiarization Time (s) |
|:--------:|:--------:|:--------:|
| Fribbuli |  Low     |     5    | 
| Fribbuli |  Low     |    10    |
| Fribbuli |  Low     |    15    |
| Fribbuli |  High    |     5    |
| Fribbuli |  High    |    10    |
| Fribbuli |  High    |    15    |
| Fractals |  Low     |     5    |
| Fractals |  Low     |    10    |
| Fractals |  Low     |    15    |
| Fractals |  High    |     5    |
| Fractals |  High    |    10    |
| Fractals |  High    |    15    |

: Familarization events *(Note: Order of events will be randomized for each pariticipant)* {#tbl-familiarization .striped}

## Test Phase

Once the familiarization criterion has been reached, the infant will be presented with a central-fixation stimulus (looming circle) for 500 ms. The central-fixation stimulus will be immediately followed by the paired test stimuli. Each pair of test stimuli includes the stimulus to which the infant was familiarized and a novel stimulus from the same stimulus class (Fribbuli or Fractals) and complexity level (low-complexity or high-complexity). Infants will view the test stimuli for a total of 10s, separated into two sub-phases. They will be presented with the familiar and novel stimulus for 5s after which a central fixation stimulus will be presented. The infant will then view the second 5s test phase, which uses the same two stimuli but with the location flipped (i.e., the image that was on the left in phase 1 will be on the right in phase 2).

