# Stimuli {#stimuli}

## Overview

> All materials are available in the [**MB5 materials directory**](https://drive.google.com/drive/folders/1ces1jzHYVV0Wx29JAtdfGAZx_pDAAh5l?usp=sharing).

Because the sample size possible in ManyBabies projects provides a unique opportunity to test generalizability across multiple stimulus types, we chose two different categories of stimuli: **Fribbuli**[^stimuli-1] and **Fractals**. These two classes of stimuli were chosen because: (1) they allow for variation in stimulus complexity within the same stimulus category (i.e., by manipulating the number of features); (2) infants are unlikely to have previous experience with either set of stimuli; and (3) the inclusion of two stimulus sets allow us to begin examining the generalizability of any observed effect.

[^stimuli-1]: "Fribbuli" is a portmenteau combining the words "Fribble" and "stimuli". These stimuli were inspired by the Fribbles stimulus set [@barry2014]

We created 12 unique Fribbuli and 12 unique Fractals, operationalizing complexity as the number of features present (these features are appendages in the case of Fribbuli and iterations of the same structure for Fractals; see Figure 3). Within each stimulus type, 6 items were designed to be low-complexity and 6 were designed to be high-complexity

### ManyFribbuli[^stimuli-2]

[^stimuli-2]: We're calling our custom sets of stimuli "ManyFribbuli" and "ManyFractals" because... well, it's fun.

Fribbuli are colorful, computer-generated models of 3D figures. All Fribbuli are made up of one of twelve possible body shapes and one (low-complexity) or four (high-complexity) appendages.

**ADD MORE INFO ABOUT COLOR SELECTION, SIZING, ETC**

### ManyFractals

Fractals are geometric shapes in which the same structure is repeated iteratively at different levels of scale.

**ADD MORE INFO ABOUT FRACTAL GENERATION**


### Attention-getter stimuli

-   **Between Trials:** Please use the provided "laughing baby" stimulus to re-center babies between each trial (i.e., before familiarization begins). If your lab uses a different attention-getting stimulus that you feel is more appropriate for your community, please check with us.
-   **Within Trial:** Please use the the "Hoehle circle with chimes" stimulus to re-center babies within each trial (i.e., between familiarization and test and between test phases 1 and 2).

