# Testing conditions {#sec-test-conditions}

## Piloting and other non-primary data

Some labs might wish to pilot their design on a small number of infants in order to work out problems with the setup and allow experimenters to practice the protocol. Piloting with this purpose is indeed encouraged! **It is critical to the integrity of the ManyBabies project that these pilot data are carefully differentiated from your main contribution.** You do NOT need to report pilot data in your spreadsheet, but if you do, please ensure that you properly mark them as such in the designated `Pilot` column.

You must make an explicit decision to begin non-pilot data collection at a particular date - this decision cannot be retroactive, and **cannot be based on inspection of the pilot data** (i.e., you cannot choose to include a pilot participant in the actual sample if the data “looks good”). Some labs might plan to test additional babies beyond the primary sample (e.g., with additional manipulations). These data will not be included in our primary planned analyses, and will not count toward the minimum contribution, but these additional data points are welcome, and we encourage researchers to preregister other hypotheses. You are free to publish these “side studies” on your own terms, but please keep in mind the restrictions on publishing the main dataset if you are using it as a comparison/control sample (see the section on Open Science Policies in the MB General Manual).

### Caregiver bias and instruction

-   Caregivers should be masked from viewing the visual stimulus using your lab’s standard method (e.g., having caregivers wear taped-over sunglasses). It is not necessary to block parents' hearing of the audio stimulus.

-   Instruct parents NOT to point to the lights or screen, shift their bodies, or move their chairs if the baby is inattentive. Emphasize during the instruction/setup that infants’ boredom with some of the stimuli is part of the experiment and is OK.

-   Suggestion: to ensure that the infant and parent are as comfortable as possible, you may tell the parent that it is okay to shift their or their baby’s body to a more comfortable position, or provide interaction that the baby is soliciting, but emphasize that this may be done only for a short period during the attention grabber phase (e.g., when they hear the laughing baby).

### Experimenter blindness

The experimenter should be masked from trial details, by being either

-    in a different room, with no way of knowing which stimuli the baby is seeing on each trial, or

-   in the same room but facing away from the stimuli and unaware of what is on the screen

### Sound volume

Your lab can use whatever volume level has been used successfully in the past, but please standardize your volume for this study so that every baby gets stimuli at the same volume.
