# Data collection period {#sec-testdates}

::: callout-important
## TEST DATES TO BE DETERMINED! {.mark .unnumbered}

# MB5 DATA COLLECTION HAS NOT YET STARTED! {.unnumbered}

## Testing start and end dates have not yet been finalized! {.unnumbered}

# DO NOT BEGIN DATA COLLECTION FOR MB5 UNTIL TESTING DATES HAVE BEEN ANNOUNCED AND PROJECT LEADS GIVE YOUR LAB A "GREEN-LIGHT"!! {.unnumbered}
:::

MB5 data collection is scheduled to run between the following dates:

#### *Start Date:* **2026-MM-DD** {.unnumbered}

#### *End Date:* **2027-MM-DD** {.unnumbered}

It is essential that all participating labs do their best to collect data prior to the End Date. However, we understand that there may be disruptions to data collection for various reasons.

**If you are having trouble meeting this deadline, please alert the Project Leads (**{{< var email.support >}}**) as soon as possible to discuss options.**

------------------------------------------------------------------------

**Labs may join the MB5 project any time during the data collection period, provided they:**

-   commit to completing data collection by the specified end date, AND
-   obtain a formal “Green Light” for testing from the Project Leads (see @sec-greenlight)
